# Copyright 2018-2025 Nick Brassel (@tzarc)
# SPDX-License-Identifier: GPL-2.0-or-later

LTO_ENABLE = yes
OPT = s
CONSOLE_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
#SHARED_EP_ENABLE = yes
#KEYBOARD_SHARED_EP = yes
#MOUSE_SHARED_EP = yes
DEBUG_MATRIX_SCAN_RATE_ENABLE = no
UNICODE_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes

XAP_ENABLE = yes
