// Copyright 2022 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-font-image -i epilepsysansbold.png -f mono4`

#pragma once

#include <qp.h>

extern const uint32_t font_epilepsysansbold_length;
extern const uint8_t  font_epilepsysansbold[1868] QP_RESIDENT_FLASH;
