// Copyright 2022 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-font-image -i hannover23.png -f mono2`

#pragma once

#include <qp.h>

extern const uint32_t font_hannover23_length;
extern const uint8_t  font_hannover23[2435] QP_RESIDENT_FLASH;
