CONSOLE_ENABLE = yes
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
UNICODE_ENABLE = yes
WPM_ENABLE = yes

DEBUG_MATRIX_SCAN_RATE_ENABLE = api

SRC += qp_rgb565_surface.c

OPT_DEFS += -DUSE_PLUG_DETECT_PIN

LUA_ENABLE = yes
