#!/bin/bash

if [[ ! -z $SIZE_REGRESSION_EXECUTING ]] ; then
    exit 0
fi

if [ "$1" = "" -o "$1" != "$2" ] ; then
    [ -e lib/littlefs ] && rm -rf lib/littlefs
    [ -e lib/lua ] && rm -rf lib/lua
    [ -e lib/lvgl ] && rm -rf lib/lvgl
    [ -e lib/pico-sdk ] && rm -rf lib/pico-sdk
    [ -e lib/ugfx ] && rm -rf lib/ugfx
    [ -e lib/chibios-contrib/ext/mcux-sdk ] && rm -rf lib/chibios-contrib/ext/mcux-sdk
    make git-submodule
    which qmk
    qmk --update
    make git-submodule
fi
