# Copyright 2018-2022 Nick Brassel (@tzarc)
# SPDX-License-Identifier: GPL-3.0-or-later
LTO_ENABLE = yes
OPT = s
XAP_ENABLE = no
RAW_ENABLE = no
#CONSOLE_ENABLE = yes
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
SHARED_EP_ENABLE = no
KEYBOARD_SHARED_EP = no
MOUSE_SHARED_EP = no
NKRO_ENABLE = no
DEBUG_MATRIX_SCAN_RATE_ENABLE = no
