# Copyright 2018-2024 Nick Brassel (@tzarc)
# SPDX-License-Identifier: GPL-2.0-or-later

LTO_ENABLE = yes
OPT = s
XAP_ENABLE = no
RAW_ENABLE = no
CONSOLE_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSE_SHARED_EP = yes
DEBUG_MATRIX_SCAN_RATE_ENABLE = no
NKRO_ENABLE = no
UNICODE_ENABLE = no
GAME_MODES_ENABLE = no
DIGITIZER_ENABLE = no
PROGRAMMABLE_BUTTON_ENABLE = no
