#pragma once

#include_next "mcuconf.h"

#ifdef SERIAL_DRIVER_USART
#undef STM32_SERIAL_USE_USART1
#define STM32_SERIAL_USE_USART1 TRUE
#endif  // SERIAL_DRIVER_USART

#ifdef SERIAL_DRIVER_USART_DUPLEX
#undef STM32_UART_USE_USART1
#define STM32_UART_USE_USART1 TRUE
#endif  // SERIAL_DRIVER_USART_DUPLEX

#undef STM32_PWM_USE_TIM4
#define STM32_PWM_USE_TIM4 TRUE
