// Copyright 2024 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `painter-convert-font-image` with arguments:
//    format         | mono4
//    unicode_glyphs | 1234Q
//    output         | src
//    input          | exocet.png

#pragma once

#include <qp.h>

extern const uint32_t font_exocet_length;
extern const uint8_t  font_exocet[606];
