// Copyright 2024 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-font-image --input /home/nickb/qmk_build/users/tzarc/graphics/src/minecraftia8.png --output /home/nickb/qmk_build/users/tzarc/graphics/src --no-ascii False --unicode-glyphs  --format mono2 --no-rle False`

#pragma once

#include <qp.h>

extern const uint32_t font_minecraftia8_length;
extern const uint8_t  font_minecraftia8[926];
