// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input /home/nickb/qmk_build/users/tzarc/graphics/wow.png --output /home/nickb/qmk_build/users/tzarc/graphics/src --format pal16 --no-rle False --no-deltas False`

#pragma once

#include <qp.h>

extern const uint32_t gfx_wow_length;
extern const uint8_t  gfx_wow[28450];
