// Copyright 2023 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-font-image -i ianhan-BitmapFonts-32X32-FA-QFF.png -f pal16`

#pragma once

#include <qp.h>

extern const uint32_t font_ianhan_BitmapFonts_32X32_FA_QFF_length;
extern const uint8_t  font_ianhan_BitmapFonts_32X32_FA_QFF[3778];
