/* Copyright 2020 QMK
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * This file was auto-generated by util/convert_gfx.py!
 */

#include "decode_luts.h"

// clang-format off

/**
  * This lookup table handles the conversion from a single 4bpp mono pixel, to a 16-bit rgb565 format pixels used natively by the TFT.
  * Each 4-bit pixel expands to the equivalent value:
  *   - The range of value in a 4-bit integer is [0,15]
  *   - Equivalent on-screen brightness translates to a linear interpolation of 16 steps between 0% brightness to 100% brightness
  *   - Each channel in the resulting rgb565 pixel needs corresponding brightness values as they're monochrome
  * This table matches a single nibble of each byte specified in the pixel data
  */

const uint16_t mono4bpp_rgb565_lookup[16] = {
    0x0000 /*   0 */, 0x8210 /*  17 */, 0x0421 /*  34 */, 0xA631 /*  51 */,
    0x2842 /*  68 */, 0xAA52 /*  85 */, 0x2C63 /* 102 */, 0xAE73 /* 119 */,
    0x518C /* 136 */, 0xD39C /* 153 */, 0x55AD /* 170 */, 0xD7BD /* 187 */,
    0x59CE /* 204 */, 0xFBDE /* 221 */, 0x7DEF /* 238 */, 0xFFFF /* 255 */,
};

/**
  * This lookup table handles the conversion from a pair of 2bpp mono pixels, to a pair of 16-bit rgb565 format pixels used natively by the TFT.
  * Each 2-bit pixel expands to the equivalent value:
  *   - The range of value in a 2-bit integer is [0,3]
  *   - Equivalent on-screen brightness translates to "off", "33% bright", "66% bright", "100% bright"
  *   - Each channel in the resulting rgb565 pixel needs corresponding brightness values as they're monochrome
  *   - For B and R, 5-bit, this corresponds to 0, 10, 20, 31
  *   - For G, 6-bit, this corresponds to 0, 21, 42, 63
  *   - Fully composed as bitmasks, this results in pixel values of 0x0000, 0x52AA, 0xA554, 0xFFFF
  * This table matches a single nibble of each byte specified in the pixel data, i.e. a pair of pixels:
  *   - Two 2-bit pixels at a time means the result is a pair of two 16-bit rgb565 pixels -- a single uint32_t is used to describe both in one value
  */

const uint32_t mono2bpp_rgb565_lookup[16] = {
    0x00000000 /*   0,   0 */, 0x0000AA52 /*   0,  85 */, 0x000055AD /*   0, 170 */, 0x0000FFFF /*   0, 255 */,
    0xAA520000 /*  85,   0 */, 0xAA52AA52 /*  85,  85 */, 0xAA5255AD /*  85, 170 */, 0xAA52FFFF /*  85, 255 */,
    0x55AD0000 /* 170,   0 */, 0x55ADAA52 /* 170,  85 */, 0x55AD55AD /* 170, 170 */, 0x55ADFFFF /* 170, 255 */,
    0xFFFF0000 /* 255,   0 */, 0xFFFFAA52 /* 255,  85 */, 0xFFFF55AD /* 255, 170 */, 0xFFFFFFFF /* 255, 255 */,
};

// clang-format on
