/* Copyright 2020 QMK
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * This file was auto-generated by util/convert_gfx.py!
 */

/* generated from badge-dark120.png */

#pragma once

// clang-format off

#include <stdint.h>

#define GFX_BADGE_DARK120_HEIGHT 35
#define GFX_BADGE_DARK120_WIDTH  120
#define GFX_BADGE_DARK120_BYTES  2100
#define GFX_BADGE_DARK120_TYPE   IMAGE_MONO4BPP

extern const uint8_t gfx_badge_dark120[2100];

// clang-format on
