// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input /Users/me/source/qmk_userspace/primeplus.png --output /Users/me/source/qmk_userspace --format mono2 --no-rle False --no-deltas False`

#pragma once

#include <qp.h>

extern const uint32_t gfx_primeplus_length;
extern const uint8_t  gfx_primeplus[317];
