networks:
  backplane:
    internal: true
  frontend:
    internal: false

services:
  squid:
    image: ubuntu/squid:latest
    restart: always
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
    networks:
      - frontend
      - backplane

  redis:
    image: redis:alpine
    restart: always
    networks:
      - backplane
    environment:
      - http_proxy=http://squid:3128
      - https_proxy=http://squid:3128
    user: "${PUID}:${PGID}"
    volumes:
      - ./data:/data
    command: redis-server --save 20 1 --appendonly yes --loglevel warning

  acceptor:
    build:
      context: ./runner
      dockerfile: Dockerfile.acceptor
    restart: always
    init: true
    ports:
      - 18000:80
    networks:
      - frontend
      - backplane
    environment:
      - TARGET_REPO=qmk/qmk_firmware
      - IGNORED_PRS=13733 # comma-separated

  worker:
    build:
      context: ./runner
      dockerfile: Dockerfile.worker
    restart: always
    init: true
    networks:
      - backplane
    environment:
      - http_proxy=http://squid:3128
      - https_proxy=http://squid:3128
    deploy:
      replicas: 4

  uploader:
    build:
      context: ./runner
      dockerfile: Dockerfile.uploader
    restart: always
    init: true
    networks:
      - frontend
      - backplane
    environment:
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK?Variable not set}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY?Variable not set}
      - AWS_SECRET=${AWS_SECRET?Variable not set}
      - S3_BUCKET=${S3_BUCKET?Variable not set}
