networks:
  backplane:
    internal: true
  frontend:
    internal: false

services:
  squid:
    image: ubuntu/squid:latest
    restart: always
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
    networks:
      - frontend
      - backplane

  redis:
    image: redis:alpine
    restart: always
    networks:
      - backplane
    environment:
      - http_proxy=http://squid:3128
      - https_proxy=http://squid:3128

  acceptor:
    build:
      context: ./runner
      dockerfile: Dockerfile.acceptor
    restart: always
    init: true
    ports:
      - 18000:80
    networks:
      - frontend
      - backplane
    environment:
      - http_proxy=http://squid:3128
      - https_proxy=http://squid:3128

  worker:
    build:
      context: ./runner
      dockerfile: Dockerfile.worker
    restart: always
    init: true
    networks:
      - backplane
    environment:
      - http_proxy=http://squid:3128
      - https_proxy=http://squid:3128
    deploy:
      replicas: 4