#!/bin/bash

set -eEuo pipefail

abs_path() {
  pushd . >/dev/null
  if [ -d "$1" ]; then
    cd "$1"
    dirs -l +0
  else
    cd "$(dirname "$1")"
    local cur_dir=$(dirs -l +0)
    if [ "${cur_dir}" == "/" ]; then
      echo "${cur_dir}$(basename "$1")"
    else
      echo "${cur_dir}/$(basename "$1")"
    fi
  fi
  popd >/dev/null
}

bash_script="$(abs_path "${BASH_SOURCE[0]}")"
script_dir="$(abs_path "$(dirname "$bash_script")")"

[ -d "$script_dir/data" ] || mkdir -p "$script_dir/data"

main() {
  PUID=$(id -u) PGID=$(id -g) docker compose pull
  PUID=$(id -u) PGID=$(id -g) docker compose build
  PUID=$(id -u) PGID=$(id -g) docker compose up -d --remove-orphans "$@"
}

main