/* Copyright 2020 QMK
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * This file was auto-generated by:
 *    `qmk chibios-confmigrate -i keyboards/l412_shiftreg/mcuconf.h -r platforms/chibios/GENERIC_STM32_L433XC/configs/mcuconf.h`
 */

#pragma once

#include_next <mcuconf.h>

#undef STM32_LSI_ENABLED
#define STM32_LSI_ENABLED FALSE

#undef STM32_PLLM_VALUE
#define STM32_PLLM_VALUE 4

#undef STM32_PLLN_VALUE
#define STM32_PLLN_VALUE 80

#undef STM32_PLLQ_VALUE
#define STM32_PLLQ_VALUE 4

#undef STM32_PLLR_VALUE
#define STM32_PLLR_VALUE 4

#undef STM32_PLLSAI1N_VALUE
#define STM32_PLLSAI1N_VALUE 72

#undef STM32_PLLSAI1Q_VALUE
#define STM32_PLLSAI1Q_VALUE 6

#undef STM32_PLLSAI1R_VALUE
#define STM32_PLLSAI1R_VALUE 6

#undef STM32_SPI_USE_SPI1
#define STM32_SPI_USE_SPI1 TRUE

