// Copyright 2024 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-font-image --input /Users/me/source/qmk_userspace/sharetech11.png --output /Users/me/source/qmk_userspace --no-ascii False --unicode-glyphs  --format mono2 --no-rle False`

#pragma once

#include <qp.h>

extern const uint32_t font_sharetech11_length;
extern const uint8_t  font_sharetech11[1175];
