name: Test PR Trigger

on:
    pull_request:
        types: [opened, synchronize]

permissions:
  contents: read

jobs:
  test_pr_trigger:
    name: "Test PR Trigger"
    runs-on: ubuntu-latest
    if: github.event.pull_request.mergeable == true
    steps:
      - name: "Prepare"
        run: |
          apt update
          apt install -y jq curl git

      - name: "Checkout base"
        uses: actions/checkout@v4
        with:
            path: base_repo
            ref: ${{ github.event.pull_request.base.sha }}

      - name: "Checkout target"
        uses: actions/checkout@v4
        with:
            path: target_repo
            ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: "List changed files"
        run: |
          echo "Base repo: $(git -C base_repo log -1)"
          echo "Target repo: $(git -C target_repo log -1)"
          echo "Diff:"
          echo git -C target_repo diff --name-only ${{ github.event.pull_request.base.sha }}
          git -C target_repo diff --name-only ${{ github.event.pull_request.base.sha }}
